version: 2
sources:
  - name: netflix
    database: dbt
    schema: netflix
    tables:
      - name: tags
        description: "Table containing user-generated tags for movies."
        columns:
          - name: user_id
            description: "Unique identifier for the user who created the tag."
          - name: movie_id
            description: "Unique identifier for the movie that the tag is associated with."
          - name: tag
            description: "The tag text provided by the user."
          - name: timestamp
            description: "The timestamp when the tag was created."
      - name: ratings
        description: "Table containing user ratings for movies."
        columns:
          - name: user_id
            description: "Unique identifier for the user who rated the movie."
          - name: movie_id
            description: "Unique identifier for the movie that was rated."
          - name: rating
            description: "The rating given by the user, typically on a scale of 1 to 5."
          - name: timestamp
            description: "The timestamp when the rating was given, formatted as a timestamp."
      - name: movies
        description: "Table containing movie metadata."
        columns:
          - name: movie_id
            description: "Unique identifier for the movie."
          - name: title
            description: "Title of the movie."
          - name: genre
            description: "Genre of the movie."
      - name: genome_tags
        description: "Table containing movie metadata."
        columns:
          - name: tag_id
            description: "Unique identifier for the tag."
          - name: tag
            description: "The tag text."

      - name: genome_scores
        description: "Table containing genome scores for movies."
        columns:   
          - name: movie_id
            description: "Unique identifier for the movie."
          - name: relevance
            description: "Unique identifier for the tag."
          - name: relevance
            description: "Relevance score of the tag for the movie, typically between 0 and 1."   

      - name: links
        description: "Table containing links between movies and external identifiers."
        columns:
          - name: movie_id
            description: "Unique identifier for the movie."
          - name: imdb_id
            description: "IMDB identifier for the movie."
          - name: tmdb_id
            description: "TMDB identifier for the movie."                        